# ======================================================================
#  Dockerfile — Next.js ecommerce_frontend_kalvin
#  Multi-stage build : deps → builder → runner
#  Target: Production-grade, minimal attack surface, non-root user
# ======================================================================

# ──────────────────────────────────────────────────────────────────────
#  STAGE 1 — deps
#  Install production + dev dependencies with a reproducible lockfile.
#  Kept separate so node_modules are cached unless package-lock changes.
# ──────────────────────────────────────────────────────────────────────
FROM node:20.18-alpine3.20 AS deps

# Security: do not run as root even during install
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid  1001 nextjs

WORKDIR /app

# Copy manifests only → better layer cache
COPY package.json package-lock.json ./

# ci = strict lockfile, no audit noise, clean install
RUN npm ci --ignore-scripts

# ──────────────────────────────────────────────────────────────────────
#  STAGE 2 — builder
#  Compile the application. Output is .next/ (standalone mode).
# ──────────────────────────────────────────────────────────────────────
FROM node:20.18-alpine3.20 AS builder

WORKDIR /app

# Bring in the installed modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the full source (excluding what .dockerignore filters)
COPY . .

# ── Build-time environment variables ────────────────────────────────
# These are NEXT_PUBLIC_* vars baked into the JS bundle at build time.
# They are injected via docker-compose build args → ARG → ENV.
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GOOGLE_MAP_KEY

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_GOOGLE_MAP_KEY=${NEXT_PUBLIC_GOOGLE_MAP_KEY}

# Disable Next.js anonymous telemetry in CI/CD
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Enable standalone output so we only ship what is needed at runtime
# (set in next.config.ts as well — see runtime stage comment)
RUN npm run build

# ──────────────────────────────────────────────────────────────────────
#  STAGE 3 — runner
#  Minimal Alpine image, only the compiled output.
#  No node_modules, no source code, no dev tooling.
# ──────────────────────────────────────────────────────────────────────
FROM node:20.18-alpine3.20 AS runner

# Harden the OS layer
RUN apk add --no-cache \
    # non-interactive timezone data for accurate server-side timestamps
    tzdata \
    # curl is useful for health-checks in orchestration (Kubernetes / ECS)
    curl \
 && rm -rf /var/cache/apk/*

WORKDIR /app

# ── Security: dedicated non-root system user ────────────────────────
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid  1001 nextjs

# ── Runtime environment ──────────────────────────────────────────────
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
# TZ is used by Node.js for date formatting
ENV TZ=Africa/Abidjan

# ── Copy compiled artefacts from builder ────────────────────────────
# public/ is served as-is (images, icons, robots.txt …)
COPY --from=builder /app/public ./public

# .next/standalone contains a self-contained server (no node_modules needed)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# .next/static contains immutable JS/CSS chunks → served by Next.js or CDN
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# ── Switch to non-root user before exposing port ─────────────────────
USER nextjs

# Port declaration (documentation; actual binding via  env)
EXPOSE 3000

# ── Healthcheck ──────────────────────────────────────────────────────
# Docker / orchestrators will restart the container if this fails.
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD curl -f http://localhost:3000/api/health || exit 1

# ── Entrypoint ───────────────────────────────────────────────────────
# server.js is generated by Next.js standalone output.
# It listens on  (default 3000).
CMD ["node", "server.js"]
